### ISSUE TITLE
ImportError: No module named builtins

### ISSUE THREAD

**Issue by wolfcry0** [kappataumu/letsencrypt-cloudflare-hook#25] opened 2016-12-10 22:42 UTC
Ubuntu Server 16.04 x64

Installed following readme file, used `pip3 install -r hooks/cloudflare/requirements.txt` to install dependencies.

`./dehydrated -c -d [domain] -t dns-01 -k 'hooks/cloudflare/hook.py'`
`# INFO: Using main config file /root/dehydrated/config`
`Processing [domain]`
` + Signing domains...`
` + Generating private key...`
` + Generating signing request...`
` + Requesting challenge for [domain]...`
`Traceback (most recent call last):`
`  File "hooks/cloudflare/hook.py", line 8, in <module>`
`    from builtins import str`
`ImportError: No module named builtins`

**Comment by kappataumu** [comment] 2016-12-11 00:38
Hello, can you post the output of `which python`, `python -V` and `pip freeze`?

**Comment by kappataumu** [comment] 2016-12-23 03:11
I think you must've made progress, so I'll go ahead and close the issue. If you are still having trouble we can resume troubleshooting.

**Closed as completed by kappataumu** 2016-12-23 03:11 UTC

**Comment by lambda-fairy** [comment] 2017-04-08 09:57
I got the same error, with Ubuntu 16.04 x64 as well.

There are two issues involved I think:

- Under Ubuntu, the `python` command links to Python 2, not 3

- In Python 2, the `builtins` module is called [`__builtin__`](https://docs.python.org/2/library/__builtin__.html) instead

I can think of two ways to solve this:

- Abandon Python 2 support, and change the shebang line to `#!/usr/bin/env python3`

- Import either `builtins` or `__builtin__` via a fallback

  ```python
  try:
      from builtins import str
  except ImportError:
      from __builtin__ import str
  ```

**Comment by YasharF** [comment] 2019-02-14 19:47
@kappataumu 
This problem still exists and the root cause has not been resolved. It just simply doesn't work on Ubuntu out of the box when following the instructions.  I have got it to work in the past, but by making changes.  I am looking to figure out how to fix this permanently.

@lfairy 
Just changing the shebang to python3 doesn't result in a full fix.  It generates the following error:
```
Traceback (most recent call last):
  File "dehydrated/hooks/cloudflare/hook.py", line 10, in <module>
    from future import standard_library
ModuleNotFoundError: No module named 'future'
```

Using the try/except block also doesn't fix it.  It generates the following error:
```
Traceback (most recent call last):
  File "dehydrated/hooks/cloudflare/hook.py", line 13, in <module>
    from future import standard_library
ModuleNotFoundError: No module named 'future'
```

**Comment by YasharF** [comment] 2019-02-14 20:32
The issue for me turned out to be the versions of cffi, cryptography and pyOpenSSL in requirements.python-2.txt.  Potentially because of some compatibility issues or deprecations they don't install properly, but modifying the requirments-python-2.txt to use the latest versions of those packages fixes the problem.  I can submit a PR for a fix.

**Comment by YasharF** [comment] 2019-02-14 20:48
Fix: https://github.com/kappataumu/letsencrypt-cloudflare-hook/pull/55
